/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/668c4091f174a74779558a36.glb 
*/

import React, { useEffect, useRef } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useControls } from "leva";
import * as THREE from "three";
export function Avatar(props) {
  const { animation } = props;
  const group = useRef();
  const { scene } = useGLTF("models/avatar.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { headFollow, cursorFollow, wireframe } = useControls({
    headFollow: false,
    cursorFollow: false,
    wireframe: false,
  });
  const { animations: typingAnimation } = useFBX("animations/Typing.fbx");
  const { animations: bicycleCrunchAnimation } = useFBX(
    "animations/Bicycle Crunch.fbx"
  );
  const { animations: fallingIdleAnimation } = useFBX(
    "animations/Falling Idle.fbx"
  );
  const { animations: maleDynamicPoseAnimation } = useFBX(
    "animations/Male Dynamic Pose.fbx"
  );
  const { animations: shufflingAnimation } = useFBX("animations/Shuffling.fbx");
  const { animations: situpAnimation } = useFBX("animations/Situps.fbx");
  const { animations: tauntAnimation } = useFBX("animations/Taunt.fbx");
  const { animations: standingIdleAnimation } = useFBX("animations/Standing Idle.fbx");

  const { animations: flairAnimation } = useFBX("animations/Flair.fbx");
  //Change the name of the animation to make it easier to call
  typingAnimation[0].name = "Typing";
  bicycleCrunchAnimation[0].name = "Bicycle Crunch";
  fallingIdleAnimation[0].name = "Falling Idle";
  maleDynamicPoseAnimation[0].name = "Male Dynamic Pose";
  shufflingAnimation[0].name = "Shuffling";
  situpAnimation[0].name = "Situps";
  tauntAnimation[0].name = "Taunt";
  flairAnimation[0].name = "Flair";
  standingIdleAnimation[0].name = "Standing Idle";
  const { actions } = useAnimations(
    [typingAnimation[0], fallingIdleAnimation[0], flairAnimation[0], tauntAnimation[0], situpAnimation[0], bicycleCrunchAnimation[0], maleDynamicPoseAnimation[0], shufflingAnimation[0], standingIdleAnimation[0]],
    group
  );
  const { nodes, materials } = useGLTF("models/avatar.glb");

  useFrame((state) => {
    //Avatar looks at the camera
    if (headFollow) {
      group.current.getObjectByName("Head").lookAt(state.camera.position);
    }
    //Avatar spine follows the cursor
    if (cursorFollow) {
      const target = new THREE.Vector3(state.mouse.x, state.mouse.y, 1);
      group.current.getObjectByName("Spine2").lookAt(target);
    }
  });

  //Play the animation
  useEffect(() => {
    //Smoothly fadein the animations
    actions[animation].reset().fadeIn(0.6).play();

    //Stop previous animation
    return () => {
      actions[animation].reset().fadeOut(0.1);
    };
  }, [animation]);

  useEffect(() => {
    //turn on/off wireframe
    Object.values(materials).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [wireframe]);
  return (
    <group {...props} dispose={null} ref={group}>
      <group>
        <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      </group>
      
    </group>
  );
}

useGLTF.preload("models/avatar.glb");
